#!/bin/sh
. /usr/share/debconf/confmodule

# The mythbuntu plugins make changes in the HOME of the new user before
# it's made, so some things need to be cleaned up

#TODO 01-10: remove me.  I'm a hack, mostly because usersetup is still not a
#ubiquity plugin.  That appears to be a pretty big task though, so i'll
#get by for now.

db_get passwd/username
CHROOT="chroot /target"
TARGET_USERNAME="$RET"
TARGET_HOME=$($CHROOT getent passwd $TARGET_USERNAME | cut -d : -f6)

$CHROOT adduser $TARGET_USERNAME mythtv
$CHROOT adduser $TARGET_USERNAME video
$CHROOT chown 1000:1000 $TARGET_HOME -R
