#! /bin/sh -e
#Passes on the information gathered in ubiquity
#about additional services
# Written by Mario Limonciello <superm1@ubuntu.com>
# Copyright (C) 2007-2008 Mario Limonciello

. /usr/share/debconf/confmodule

if [ "$1" ]; then
    ROOT="$1"
    chroot=chroot
    log='log-output -t mythbuntu'
fi

vnc_config()
{
    db_get mythbuntu/x11vnc_password
    VNC_PASS="$RET"
    cat > /tmp/vnc_pass_script <<EOF
#!/usr/bin/expect
set PASS "$VNC_PASS"
spawn vncpasswd /tmp/vnc-passwd
expect Password: { send \$PASS; send "\r" }
expect Verify: { send \$PASS; send "\r"}
expect eof exit 0
EOF
    chmod +x /tmp/vnc_pass_script
    /tmp/vnc_pass_script
    mkdir -p $ROOT/root/.vnc
    mv /tmp/vnc-passwd $ROOT/root/.vnc/passwd
    chmod a+r $ROOT/root/.vnc/passwd
    rm /tmp/vnc_pass_script
}

mysql_config()
{
    MYSQLCONFIG="${ROOT}/etc/mysql/conf.d/mythtv.cnf"
    sed s/^\#bind-address/bind-address/ ${MYSQLCONFIG} | tee ${MYSQLCONFIG}.new > /dev/null
    mv ${MYSQLCONFIG}.new ${MYSQLCONFIG}
}

db_get mythbuntu/x11vnc
VNC="$RET"
db_get mythbuntu/mysql-server
MYSQL="$RET"
if [ "$VNC" = true ]; then
    vnc_config
fi
if [ "$MYSQL" = true ]; then
    mysql_config
fi

exit 0
