#!/bin/sh -e
#Provides all mythbuntu questions asked by
#ubiquity during install process
# Written by Mario Limonciello <superm1@ubuntu.com>
# Copyright (C) 2007-2008 Mario Limonciello
# Copyright (C) 2007 Jared Greenwald

. /usr/share/debconf/confmodule

#determine services
db_input high mythbuntu/x11vnc || true
db_input high mythbuntu/x11vnc_password || true
db_input high mythbuntu/openssh-server || true
db_input high mythbuntu/samba || true
db_input high mythbuntu/nfs-kernel-server || true
db_input high mythbuntu/mysql-server || true
