#! /bin/sh
#set -e

. /usr/share/debconf/confmodule

#Installation Type
db_get mythbuntu/install_type
db_subst mythbuntu/summary INSTALLTYPE "$RET"

#Plugins
db_get mythbuntu/mytharchive
db_subst mythbuntu/summary MYTHARCHIVE "$RET"
db_get mythbuntu/mythbrowser
db_subst mythbuntu/summary MYTHBROWSER "$RET"
db_get mythbuntu/mythcontrols
db_subst mythbuntu/summary MYTHCONTROLS "$RET"
db_get mythbuntu/mythdvd
db_subst mythbuntu/summary MYTHDVD "$RET"
db_get mythbuntu/mythflix
db_subst mythbuntu/summary MYTHFLIX "$RET"
db_get mythbuntu/mythgallery
db_subst mythbuntu/summary MYTHGALLERY "$RET"
db_get mythbuntu/mythgame
db_subst mythbuntu/summary MYTHGAME "$RET"
db_get mythbuntu/mythmusic
db_subst mythbuntu/summary MYTHMUSIC "$RET"
db_get mythbuntu/mythnews
db_subst mythbuntu/summary MYTHNEWS "$RET"
db_get mythbuntu/mythphone
db_subst mythbuntu/summary MYTHPHONE "$RET"
db_get mythbuntu/mythvideo
db_subst mythbuntu/summary MYTHVIDEO "$RET"
db_get mythbuntu/mythweather
db_subst mythbuntu/summary MYTHWEATHER "$RET"
db_get mythbuntu/mythweb
db_subst mythbuntu/summary MYTHWEB "$RET"

#Themes
db_get mythbuntu/officialthemes
db_subst mythbuntu/summary OFFICIAL "$RET"
db_get mythbuntu/communitythemes
db_subst mythbuntu/summary COMMUNITY "$RET"

#Services
db_get mythbuntu/vncservice
db_subst mythbuntu/summary EN_VNC "$RET"
db_get mythbuntu/vnc_password
db_subst mythbuntu/summary VNCPASS "$RET"
db_get mythbuntu/sshservice
db_subst mythbuntu/summary EN_OPENSSH "$RET"
db_get mythbuntu/sambaservice
db_subst mythbuntu/summary EN_SAMBA "$RET"
db_get mythbuntu/nfsservice
db_subst mythbuntu/summary EN_NFS "$RET"
db_get mythbuntu/mysqlservice
db_subst mythbuntu/summary EN_MYSQL "$RET"

#Drivers
db_get mythbuntu/proprietary_driver
db_subst mythbuntu/summary PROPRIETARY_VIDEO_DRIVER "$RET"
db_get mythbuntu/tvout
db_subst mythbuntu/summary TVOUT "$RET"
db_get mythbuntu/tvstandard
db_subst mythbuntu/summary TVSTANDARD "$RET"

#Mythweb Htaccess Password
#TODO: <superm1@ubuntu.com>

#MySQL Root Password
db_get mythtv/mysql_admin_password
db_subst mythbuntu/summary MYSQLROOT "$RET"

#MythTV MySQL Passwords
db_get mythtv/mysql_mythtv_user
if [ -z "$RET" ]; then
    db_set mythtv/mysql_mythtv_user "mythtv"
    db_subst mythbuntu/summary MYSQLUSER "mythtv"
else
    db_subst mythbuntu/summary MYSQLUSER "$RET"
fi
db_get mythtv/mysql_mythtv_password
if [ -z "$RET" ]; then
    #set +e
    NEW="$(pwgen -s 8)"
    #set -e
    db_set mythtv/mysql_mythtv_password "$NEW"
    db_subst mythbuntu/summary MYSQLPASS "$NEW"
else
    db_subst mythbuntu/summary MYSQLPASS "$RET"
fi
db_get mythtv/mysql_host
if [ -z "$RET" ]; then
    db_set mythtv/mysql_host "localhost"
    db_subst mythbuntu/summary MYSQLSERVER "localhost"
else
    db_subst mythbuntu/summary MYSQLSERVER "$RET"
fi
db_get mythtv/mysql_mythtv_dbname
if [ -z "$RET" ]; then
    db_set mythtv/mysql_mythtv_dbname "mythconverg"
    db_subst mythbuntu/summary MYSQLDATABASE "mythconverg"
else
    db_subst mythbuntu/summary MYSQLDATABASE "$RET"
fi

#Normal Ubuntu Questions
db_get languagechooser/language-name
db_subst mythbuntu/summary LANGUAGE "$RET"
if db_get console-setup/variant && [ "$RET" ]; then
    db_subst mythbuntu/summary KEYMAP "$RET"
else
    db_get console-setup/layout
    db_subst mythbuntu/summary KEYMAP "$RET"
fi
db_get passwd/user-fullname
db_subst mythbuntu/summary FULLNAME "$RET"
db_get passwd/username
db_subst mythbuntu/summary USERNAME "$RET"
db_get time/zone # actually continent/city (usually)
db_subst mythbuntu/summary LOCATION "$RET"

db_capb escape
db_get ubiquity/partman-made-changes
if [ "$RET" = true ]; then
    db_metaget partman/confirm Extended_description
else
    db_metaget partman/confirm_nochanges Extended_description
fi
db_subst mythbuntu/summary PARTMAN_CHANGES \
    "$(printf %s "$RET" | debconf-escape -e)"
db_capb

db_input high mythbuntu/summary || true
db_go

exit 0
