#! /bin/sh

# This program handles OEM installations: it is run on the first boot after
# the end user receives the system, to configure settings specific to that
# end user.

exec /usr/lib/oem-config/wizard.py "$@"
