#! /bin/sh
# Run oem-config on the first boot after shipping to the end user.
set -e

# Remove the temporary OEM configuration user, if possible.
deluser --quiet --remove-home oem || true
# Revert to creating a user at uid 1000.
echo RESET passwd/user-uid | debconf-communicate

/usr/sbin/oem-config-dm vt7 :0 /usr/sbin/oem-config

exit 0
