#!/bin/sh

warning() {
	zenity --info --text "No fue posible desmontar alguna de las unidades de disco.

Ha de desmontarlas usted mismo antes de proseguir con la instalación."
}
warning_swap() {
	zenity --info --text "No fue posible desmontar alguna de las unidades de swap.

Ha de desmontarlas usted mismo antes de proseguir con la instalación."
}

info() {
	zenity --info --text "Se va a proceder a desmontar las unidades de disco locales para llevar a cabo un proceso de instalación limpio."
}

info

umount_units() {
	errors=0
	for dev_array in $( cat /proc/mounts | grep -v iso9660 | cut -d" " -f1 | sort | uniq )
	do dev="$( echo $dev_array | grep ^/dev/[hs]d[a-z][0-9]*$ )"
	  if [ ! -z "$dev" ]; then
	    sudo umount -f $dev 2> /dev/null || let errors=errors+1
	  fi
	  if [ $errors -gt 0 ]; then
	    warning
	    return 1
	  fi
	done
	return 0
}

umount_swaps() {
	errors=0
	for dev_array in $( cat /proc/swaps | cut -d" " -f1 )
	do dev="$( echo $dev_array | grep ^/dev/[hs]d[a-z][0-9]*$ )"
	  if [ ! -z "$dev" ]; then
	    sudo swapoff $dev || let errors=errors+1
	    echo $errors
	  fi
	  if [ $errors -gt 0 ]; then
	    warning_swap
	    return 1
	  fi

	done
	return 0
}

umount_units && umount_swaps && /usr/bin/gksudo /usr/bin/installer &
