#!/usr/bin/python

import unittest
import os
import sys
import subprocess

os.environ['DEBCONF_SYSTEMRC'] = 'tests/debconf.conf'
sys.path.insert(0, '.')

# Build dependencies for the tests.
subprocess.check_call(['tests/build'])

# Parts borrowed from jockey.

if len(sys.argv) > 1:
    filter = sys.argv[1]
    sys.argv = sys.argv[0:1] + sys.argv[2:]
else:
    filter = ''

tests = [t[:-3] for t in os.listdir('tests')
         if t.startswith('test_') and t.endswith('.py') and filter in t]
tests.sort()
suite = unittest.TestLoader().loadTestsFromNames(tests)
res = unittest.TextTestRunner(verbosity=2).run(suite)
if res.errors or res.failures:
    sys.exit(1)
