#!/usr/bin/python

import unittest
import sys
# Make sure we're working in the source tree.
sys.path.insert(0, '.')

#class BaseFrontendTests(unittest.TestCase):
#    def setUp(self):
#        from ubiquity.frontend import base
#        self.frontend = base.BaseFrontend('ubiquity')
#
#    def tearDown(self):
#        self.frontend.stop_debconf()
        
class CoreFrontendTests:
    def testPluginsLoadProperly(self):
        should_load = ['ubi-language', 'ubi-timezone', 'ubi-console-setup',
                       'ubi-partman', 'ubi-usersetup', 'ubi-summary']
        plugins = [x.filter_class.__module__ for x in self.frontend.pages]
        for x in should_load:
            assert x in plugins, '%s not in %s' % (x, str(plugins))
    
    def testReturnToPartitioner(self):
        self.frontend.installing = True
        self.frontend.next.set_label('Install')
        self.frontend.return_to_partitioning()
        assert self.frontend.dbfilter.__module__ == 'ubi-partman'
        assert self.frontend.dbfilter.ui.__module__ == 'ubi-partman'
        assert self.frontend.next.get_label() == '_Forward'

    def tearDown(self):
        # Needed?
        self.frontend.quit_main_loop()
        self.frontend.stop_debconf()

# KDE applications run klauncher (kdelibs/kinit/klauncher_main.cpp), which
# tries to connect to the D-Bus session bus.  This wont work here as the system
# policy prevents one user from connecting to another's session bus.

#class KdeFrontendTests(CoreFrontendTests, unittest.TestCase):
#    def setUp(self):
#        from ubiquity.frontend import kde_ui
#        self.frontend = kde_ui.Wizard('ubuntu')

# The noninteractive frontend needs access to /dev/console.

#class NoninteractiveFrontendTests(CoreFrontendTests, unittest.TestCase):
#    def setUp(self):
#        from ubiquity.frontend import noninteractive
#        self.frontend = noninteractive.Wizard('ubuntu')

class GtkFrontendTests(CoreFrontendTests, unittest.TestCase):
    def setUp(self):
        from ubiquity.frontend import gtk_ui
        self.frontend = gtk_ui.Wizard('ubuntu')

if __name__ == '__main__':
    unittest.main()
