#! /bin/sh -e
mkdir -p /var/lib/ubiquity
for package; do
	echo "$package" >> /var/lib/ubiquity/apt-installed
done
# TODO: use chroot-setup
DEBIAN_FRONTEND=noninteractive DEBCONF_ADMIN_EMAIL= chroot /target apt-get --no-upgrade -o Acquire::gpgv::Options::=--ignore-time-conflict -y install "$@" </dev/null
