installer usr/bin
ubuntu-express usr/bin
espresso/*.py usr/lib/python2.4/site-packages/espresso
espresso/backend usr/lib/python2.4/site-packages/espresso
espresso/components usr/lib/python2.4/site-packages/espresso
espresso/frontend/noui.py usr/lib/python2.4/site-packages/espresso/frontend
espresso/frontend/__init__.py usr/lib/python2.4/site-packages/espresso/frontend
compat/* usr/lib/espresso/compat
