#d-i pieces
scripts/mythbuntu-ask usr/share/ubiquity
scripts/mythbuntu-apply usr/share/ubiquity
scripts/mythbuntu-drivers usr/share/ubiquity
scripts/mythbuntu-services usr/share/ubiquity
scripts/mythbuntu-setup usr/share/ubiquity

#individual python components
ubiquity/components/mythbuntu.py usr/lib/ubiquity/ubiquity/components
ubiquity/components/mythbuntu_apply.py usr/lib/ubiquity/ubiquity/components
ubiquity/components/mythbuntu_drivers.py usr/lib/ubiquity/ubiquity/components
ubiquity/components/mythbuntu_services.py usr/lib/ubiquity/ubiquity/components

#GTK/glade
ubiquity/frontend/mythbuntu_ui.py usr/lib/ubiquity/ubiquity/frontend
gui/glade/mythbuntu*.glade usr/share/ubiquity/glade

#Summary Generation Page
ubiquity/components/mythbuntu_summary.py usr/lib/ubiquity/ubiquity/components
scripts/mythbuntu_summary usr/share/ubiquity

#GTK->Final installer glue
ubiquity/components/mythbuntu_install.py usr/lib/ubiquity/ubiquity/components

#Final Installer piece
scripts/mythbuntu_install.py usr/share/ubiquity
