#d-i pieces
scripts/mythbuntu/* usr/share/ubiquity

#individual python components
ubiquity/components/mythbuntu.py usr/lib/ubiquity/ubiquity/components
ubiquity/components/mythbuntu_apply.py usr/lib/ubiquity/ubiquity/components
ubiquity/components/mythbuntu_drivers.py usr/lib/ubiquity/ubiquity/components
ubiquity/components/mythbuntu_services.py usr/lib/ubiquity/ubiquity/components

#GTK/glade
ubiquity/frontend/mythbuntu_ui.py usr/lib/ubiquity/ubiquity/frontend
gui/glade/mythbuntu*.glade usr/share/ubiquity/glade

#Summary Generation Page
ubiquity/components/mythbuntu_summary.py usr/lib/ubiquity/ubiquity/components

#GTK->Final installer glue
ubiquity/components/mythbuntu_install.py usr/lib/ubiquity/ubiquity/components
