#! /bin/sh
set -e

if [ -d /target/home/oem ]; then
	for file in \
	    /usr/share/applications/oem-config-prepare-gtk.desktop \
	    /usr/share/applications/kde/oem-config-prepare-kde.desktop; do
		if [ -f "/target$file" ]; then
			chroot /target install -d -o oem -g oem \
				/home/oem/Desktop
			chroot /target install -o oem -g oem \
				"$file" "/home/oem/Desktop/$(basename "$file")"
			break
		fi
	done
fi

# cf. casper/scripts/casper-bottom/15autologin and
# oem-config:disable_autologin()

# chroot needed to handle symlinks correctly
if chroot /target [ -f /etc/gdm/gdm-cdd.conf ]; then
	GDMCONF=/etc/gdm/gdm-cdd.conf
else
	GDMCONF=/etc/gdm/gdm.conf
fi

# chroot needed to handle symlinks correctly
if chroot /target [ -f "$GDMCONF" ]; then
	# Configure GDM autologin
	chroot /target sed -i.oem \
		-e "s/^AutomaticLoginEnable=.*\$/AutomaticLoginEnable=true/" \
		-e "s/^AutomaticLogin=.*\$/AutomaticLogin=oem/" \
		-e "s/^TimedLoginEnable=.*\$/TimedLoginEnable=true/" \
		-e "s/^TimedLogin=.*\$/TimedLogin=oem/" \
		-e "s/^TimedLoginDelay=.*\$/TimedLoginDelay=10/" \
		"$GDMCONF"
fi

if [ -f /target/etc/kde3/kdm/kdmrc ]; then
	# Configure KDM autologin
	chroot /target sed -i.oem -r \
		-e "s/^#?AutoLoginEnable=.*\$/AutoLoginEnable=true/" \
		-e "s/^#?AutoLoginUser=.*\$/AutoLoginUser=oem/" \
		-e "s/^#?AutoReLogin=.*\$/AutoReLogin=true/" \
		/etc/kde3/kdm/kdmrc
fi

if chroot /target /usr/bin/which kpersonalizer >/dev/null; then
	# Disable first-login wizard for KDE
	if [ ! -f /target/etc/kde3/kpersonalizerrc ]; then
		cat > /target/etc/kde3/kpersonalizerrc <<EOF
[General]
FirstLogin=false
EOF
		touch /target/etc/kde3/kpersonalizerrc.created-by-oem
	fi
fi

exit 0
