#! /bin/sh
set -e

. /usr/share/debconf/confmodule

export PATH="/usr/lib/oem-config/compat:/usr/lib/oem-config/keyboard:$PATH"

kbd-chooser

# TODO cjwatson 2006-07-07: cloned-and-hacked from
# kbd-chooser/debian/finish-install

db_get debian-installer/keymap
KEYMAP=$RET
# Silently exit if no keymap is set
if [ -z "$KEYMAP" ]; then
	exit 0
fi

# Install non-Unicode variants of Turkish keymaps
if [ "$KEYMAP" = "trqu" ]; then
	KEYMAP="trq"
	db_set debian-installer/keymap $KEYMAP
fi
if [ "$KEYMAP" = "trfu" ]; then
	KEYMAP="trf"
	db_set debian-installer/keymap $KEYMAP
fi

# FIXME Workaround to install some keymaps properly
case "$KEYMAP" in
trq|trf|hebrew|lt|lv-latin4|ua)
	kbd_mode_temp="ascii" ;;
*)
	kbd_mode_temp=""      ;;
esac

[ -n "$kbd_mode_temp" ] && kbd-mode --$kbd_mode_temp
install-keymap $KEYMAP
[ -n "$kbd_mode_temp" ] && kbd-mode --unicode

exit 0
