#! /bin/sh
set -e

. /usr/share/debconf/confmodule

supported () {
	grep -q "^$1 " /usr/share/i18n/SUPPORTED
}

# Recover from broken debian-installer/locale settings.
db_get debian-installer/locale
LOCALE="$RET"
if ! supported "$LOCALE"; then
	db_set debian-installer/locale ''
fi

PATH="/usr/lib/oem-config/compat:/usr/lib/oem-config/language:$PATH" \
OVERRIDE_SHOW_ALL_LANGUAGES=1 \
	localechooser
