#! /bin/sh
set -e

. /usr/share/debconf/confmodule

db_get languagechooser/language-name
db_subst ubiquity/summary LANGUAGE "$RET"
db_get debian-installer/keymap
db_subst ubiquity/summary KEYMAP "$RET"
db_get passwd/user-fullname
db_subst ubiquity/summary FULLNAME "$RET"
db_get passwd/username
db_subst ubiquity/summary USERNAME "$RET"
db_get time/zone # actually continent/city (usually)
db_subst ubiquity/summary LOCATION "$RET"

db_input high ubiquity/summary || true
db_go

exit 0
