#!/usr/bin/python

import os
import syslog
import sys

from gi.repository import GnomeKeyring, GLib

if __name__ == "__main__":

    if not "DBUS_SESSION_BUS_ADDRESS" in os.environ:
        os.environ["DBUS_SESSION_BUS_ADDRESS"] = "autolaunch:"

    password = sys.stdin.readline().strip("\n")
    token = sys.stdin.readline().strip("\n")

    # we create the keyring using the users login password
    KEYRING_NAME = os.environ.get("U1_TEST_KEYRING_NAME", "login")
    TOKEN_NAME = "Ubuntu One"

    res = GnomeKeyring.create_sync(KEYRING_NAME, password)

    if res != GnomeKeyring.Result.OK:
        syslog.syslog("failed to create keyring '%s': %s" % (KEYRING_NAME, res))        
        sys.exit(1)

    (status, item_id) = GnomeKeyring.item_create_sync(
        KEYRING_NAME,
        GnomeKeyring.ItemType.GENERIC_SECRET,
        TOKEN_NAME,
        GLib.Array(),
        token,
        True)
    if status != GnomeKeyring.Result.OK:
        syslog.syslog("failed to create item '%s': %s" % (TOKEN_NAME, res))
        sys.exit(1)

    syslog.syslog("Success, created item %r in keyring %r" % (TOKEN_NAME, KEYRING_NAME))
