#!/bin/sh
set -e
set -x

. /lib/partman/lib/base.sh

mountpoint="$(mktemp -d)"
root=
var=

fail () {
	if [ -n "$var" ] && [ -e "$mountpoint/var" ]; then
		umount "$mountpoint/var" || true
	fi
	if [ -e "$mountpoint" ]; then
		umount "$mountpoint" && rmdir "$mountpoint" || true
	fi
	db_progress STOP
	# TODO input an error question.
	exit 1
}

db_progress START 0 2 ubiquity/install/title
db_progress INFO ubiquity/install/apt_clone_save

for dev in $DEVICES/*; do
	[ -d "$dev" ] || continue
	cd $dev
	open_dialog PARTITIONS
	while { read_line num id size type fs path name; [ "$id" ]; }; do
		[ -f "$id/method" ] || continue
		[ -f "$id/use_filesystem" ] || continue
		[ -f "$id/mountpoint" ] || continue
		[ "$fs" != free ] || continue
		[ -f "$id/format" ] && continue
		[ -f "$id/formatted" ] && continue
		if [ "$(cat "$id/mountpoint")" = "/" ]; then
			root="$path"
		elif [ "$(cat "$id/mountpoint")" = "/var" ]; then
			var="$path"
		fi
	done
	close_dialog
done

db_progress STEP 1

if [ -z "$root" ]; then
	# The partition is going to be formatted; there's nothing to preserve.
	exit 0
fi
mount "$root" "$mountpoint"
[ -n "$var" ] && mount "$var" "$mountpoint/var"

working="$mountpoint/ubiquity-apt-clone"

mkdir -p "$working"
if ! /usr/share/ubiquity/apt-clone clone "$mountpoint" "$working"; then
	# TODO: if the above fails, ask a debconf error question.
	fail
fi

db_progress STEP 1

if [ -n "$var" ] && [ -e "$mountpoint/var" ]; then
	umount "$mountpoint/var" || true
fi
if [ -e "$mountpoint" ]; then
	umount "$mountpoint" && rmdir "$mountpoint" || true
fi

db_progress STOP

# TODO: finish-install.d script.

# TODO: oh bother. clear_partitions grabs passwd/username, which wont even
# exist at that point, let alone the fact that it's in a different copy of the
# database.  Check in user-setup to see if /home/$user already exists and set
# passwd/user-uid just as we do in clear_partitions.
